#!/usr/bin/env php
<?php

// Yes, I script in PHP.
// And yes, I still make fun of it.

// Lazy
define('NL', "\n");

if($_SERVER['argc'] < 2)
{
    echo 'Usage: '.$_SERVER['argv'][0].' file1.txt [file2.txt ...] >all.txt'.NL;
}

$all = [];
for($i = 1; $i < $_SERVER['argc']; ++$i)
{
    $lines = explode(NL, file_get_contents($_SERVER['argv'][$i]));
    $cur = NULL;
    foreach($lines as $l)
    {
        if(strlen($l) == 0)
        {
            // Skip
        }
        else if($l[0] == '-')
        {
            $cur[] = $l;
        }
        else
        {
            unset($cur);
            $cur = [];
            $all[$l] = &$cur;
        }
    }
    unset($cur);
}
ksort($all);
foreach($all as $k => $v)
{
    echo $k.NL;
    foreach($v as $l) // Easier to use than implode() in the case of 0 elements (which happens often)
    {
        echo $l.NL;
    }
}
